[project]
dependencies    = [
    "loguru>=0.7.3",
    "pyochain>=0.5.52",
]
description     = "Simple tool to run doctests from Python stub files (.pyi) and regular Python files (.py)."
name            = "doctester"
readme          = "README.md"
requires-python = ">=3.12"
version         = "0.1.3"
[build-system]
build-backend = "uv_build"
requires      = ["uv_build>=0.8.15,<0.9.0"]
